"""prevent duplicate findings

Revision ID: 2ceacb846a0c
Revises: c88581ebed54
Create Date: 2026-08-19 09:19:47.588187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ceacb846a0c'
down_revision: Union[str, Sequence[str], None] = 'c88581ebed54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_findings_run_chunk', 'findings', ['run_id', 'chunk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_findings_run_chunk', 'findings', type_='unique')
    # ### end Alembic commands ###
